Fixed syntax for s3_resources list
Updated to be a list for s3_resources, otherwise, TF will return an error.

```
Error: Error asking for user input: 1 error(s) occurred:

* module.s3_user.var.s3_resources: variable s3_resources in module s3_user should be type list, got string
```